# Generated by Django 6.0.4 on 2026-05-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal_user', 'Job Seeker'), ('recruiter', 'Recruiter')], default='normal_user', max_length=20),
        ),
    ]
