# Generated by Django 6.0.3 on 2026-05-15 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(default='Put your Cover Letter here', max_length=1000)),
                ('experience', models.TextField(default='No Experience', max_length=750)),
                ('skills', models.CharField(blank=True, max_length=250)),
                ('availability_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship')], default='full_time', max_length=15)),
                ('availability_period', models.CharField(default='Immediate', help_text='e.g. Immediate, 2 weeks, 1 month', max_length=50)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.CharField(choices=[('strong', 'Strong Candidate'), ('weak', 'Weak Candidate'), ('review', 'Needs Review')], default='review', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('website', 'Website')], max_length=20)),
                ('url', models.URLField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='applications.application')),
            ],
        ),
    ]
