# Generated by Django 6.0.4 on 2026-05-08 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability_period',
            field=models.CharField(default='Immediate', help_text='e.g. Immediate, 2 weeks, 1 month', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='availability_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship')], default='full_time', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(default='Put your Cover Letter here', max_length=1000),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.TextField(default='No Experience', max_length=750),
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=models.CharField(choices=[('strong', 'Strong Candidate'), ('weak', 'Weak Candidate'), ('review', 'Needs Review')], default='review', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('website', 'Website')], max_length=20)),
                ('url', models.URLField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='applications.application')),
            ],
        ),
    ]
