# Generated by Django 6.0.4 on 2026-07-22 10:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
        ('jobs', '0003_rename_user_job_recruiter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='applicant',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
    ]
