# Generated by Django 6.0.4 on 2026-07-22 10:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='recruiter',
        ),
        migrations.RenameField(
            model_name='savedjob',
            old_name='user',
            new_name='applicant',
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('applicant', 'job')},
        ),
    ]
