# Generated by Django 6.0.3 on 2026-04-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
