# Generated by Django 6.0.4 on 2026-04-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
