# Generated by Django 6.0.3 on 2026-04-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0011_remove_userprofile_user_delete_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='application',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
