# Generated by Django 6.0.3 on 2026-04-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0012_remove_notification_application_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
